Test

diff --git a/k8s/migration/Makefile b/k8s/migration/Makefile
--- a/k8s/migration/Makefile
+++ b/k8s/migration/Makefile
@@ -1,13 +1,7 @@
-REPO ?= platform9
-REGISTRY ?= quay.io
-TAG ?= 0.1.13
-
-export CONTROLLER_IMG ?= ${REGISTRY}/${REPO}/vjailbreak-controller:${TAG}
-export V2V_IMG ?= ${REGISTRY}/${REPO}/vjailbreak-v2v:${TAG}
-export VPWNED_IMG ?= ${REGISTRY}/${REPO}/vjailbreak-vpwned:${TAG}
-
+# Image URL to use all building/pushing image targets
+IMG ?= vjailbreak/migration-controller:latest
 # ENVTEST_K8S_VERSION refers to the version of kubebuilder assets to be downloaded by envtest binary.
-ENVTEST_K8S_VERSION = 1.30.0
+ENVTEST_K8S_VERSION = 1.28.0
 
 # Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
 ifeq (,$(shell go env GOBIN))
@@ -15,12 +9,6 @@ GOBIN=$(shell go env GOPATH)/bin
 else
 GOBIN=$(shell go env GOBIN)
 endif
-
-# CONTAINER_TOOL defines the container tool to be used for building images.
-# Be aware that the target commands are only tested with Docker which is
-# scaffolded by default. However, you might want to replace it to use other
-# tools. (i.e. podman)
-CONTAINER_TOOL ?= docker
 
 # Setting SHELL to bash allows bash commands to be executed by recipes.
 # Options are set to exit when a recipe line exits non-zero or a piped command fails.
@@ -34,7 +22,7 @@ all: build
 
 # The help target prints out all targets with their descriptions organized
 # beneath their categories. The categories are represented by '##@' and the
-# target descriptions by '##'. The awk command is responsible for reading the
+# target descriptions by '##'. The awk commands is responsible for reading the
 # entire set of makefiles included in this invocation, looking for lines of the
 # file as xyz: ## something, and then pretty-format the target and help. Then,
 # if there's a line with ##@ something, that gets pretty-printed as a category.
@@ -51,7 +39,7 @@ help: ## Display this help.
 
 .PHONY: manifests
 manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
-	$(CONTROLLER_GEN) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases crd:allowDangerousTypes=true
+	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
 
 .PHONY: generate
 generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
@@ -67,66 +55,49 @@ vet: ## Run go vet against code.
 
 .PHONY: test
 test: manifests generate fmt vet envtest ## Run tests.
-	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test $$(go list ./... | grep -v /e2e) -coverprofile cover.out
+	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./... -coverprofile cover.out
 
-# Utilize Kind or modify the e2e tests to load the image locally, enabling compatibility with other vendors.
-.PHONY: test-e2e  # Run the e2e tests against a Kind k8s instance that is spun up.
-test-e2e:
-	go test ./test/e2e/ -v -ginkgo.v
-
-.PHONY: lint
-lint: golangci-lint ## Run golangci-lint linter
-	$(GOLANGCI_LINT) run
-
-.PHONY: lint-fix
-lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes
-	$(GOLANGCI_LINT) run --fix
+.PHONY: test-sharedrdm
+test-sharedrdm: manifests generate fmt vet envtest ## Run SharedRDM controller tests only.
+	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./internal/controller/sharedrdm_controller_test.go -coverprofile cover-sharedrdm.out
 
 ##@ Build
 
 .PHONY: build
-build: manifests generate # fmt vet ## Build manager binary.
-	CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -ldflags "-X github.com/platform9/vjailbreak/k8s/migration/internal/controller.v2vimage=${V2V_IMG}" -o manager cmd/main.go
+build: manifests generate fmt vet ## Build manager binary.
+	go build -o bin/manager cmd/main.go
 
 .PHONY: run
 run: manifests generate fmt vet ## Run a controller from your host.
 	go run ./cmd/main.go
 
-# If you wish to build the manager image targeting other platforms you can use the --platform flag.
-# (i.e. docker build --platform linux/arm64). However, you must enable docker buildKit for it.
-# More info: https://docs.docker.com/develop/develop-images/build_enhancements/
+# If you wish built the manager image targeting other platforms you can use the --platform flag.
+# (i.e. docker build --platform linux/arm64 ). However, you must enable docker buildKit for it.
+# More info: https://docs.docker.com/develop/dev-best-practices/
 .PHONY: docker-build
-docker-build: build ## Build docker image with the manager.
-	$(CONTAINER_TOOL) build --build-arg V2V_IMG=$(V2V_IMG) --platform linux/amd64 -t ${CONTROLLER_IMG} .
+docker-build: test ## Build docker image with the manager.
+	docker build -t ${IMG} .
 
 .PHONY: docker-push
 docker-push: ## Push docker image with the manager.
-	$(CONTAINER_TOOL) push ${CONTROLLER_IMG}
+	docker push ${IMG}
 
-# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
+# PLATFORMS defines the target platforms for  the manager image be build to provide support to multiple
 # architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
-# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
-# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
-# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
-# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
+# - able to use docker buildx . More info: https://docs.docker.com/build/buildx/
+# - have a multi-arch builder. More info: https://docs.docker.com/build/building/multi-platform/
+# - be able to push the image for your registry (i.e. if you do not inform a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
+# To properly provided solutions that supports more than one platform you should use this option.
 PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
 .PHONY: docker-buildx
-docker-buildx: ## Build and push docker image for the manager for cross-platform support
+docker-buildx: test ## Build and push docker image for the manager for cross-platform support
 	# copy existing Dockerfile and insert --platform=${BUILDPLATFORM} into Dockerfile.cross, and preserve the original Dockerfile
 	sed -e '1 s/\(^FROM\)/FROM --platform=\$$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
-	- $(CONTAINER_TOOL) buildx create --name migration-builder
-	$(CONTAINER_TOOL) buildx use migration-builder
-	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) --tag ${CONTROLLER_IMG} -f Dockerfile.cross .
-	- $(CONTAINER_TOOL) buildx rm migration-builder
+	- docker buildx create --name project-v3-builder
+	docker buildx use project-v3-builder
+	- docker buildx build --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile.cross .
+	- docker buildx rm project-v3-builder
 	rm Dockerfile.cross
-
-.PHONY: build-installer
-build-installer: manifests generate kustomize ## Generate a consolidated YAML with CRDs and deployment.
-	mkdir -p dist
-	cd config/manager && $(KUSTOMIZE) edit set image controller=${CONTROLLER_IMG}
-	cd config/addons && $(KUSTOMIZE) edit set image vpwned=${VPWNED_IMG}
-	$(KUSTOMIZE) build config/default > dist/install.yaml
-	cp dist/install.yaml ../../deploy/00crds.yaml
 
 ##@ Deployment
 
@@ -136,22 +107,26 @@ endif
 
 .PHONY: install
 install: manifests kustomize ## Install CRDs into the K8s cluster specified in ~/.kube/config.
-	$(KUSTOMIZE) build config/crd | $(KUBECTL) apply -f -
+	$(KUSTOMIZE) build config/crd | kubectl apply -f -
+
+.PHONY: install-sharedrdm-crds
+install-sharedrdm-crds: manifests kustomize ## Install only SharedRDM CRDs into the K8s cluster.
+	$(KUSTOMIZE) build config/crd | kubectl apply -f - --selector=app.kubernetes.io/name=sharedrdm
 
 .PHONY: uninstall
 uninstall: manifests kustomize ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
-	$(KUSTOMIZE) build config/crd | $(KUBECTL) delete --ignore-not-found=$(ignore-not-found) -f -
+	$(KUSTOMIZE) build config/crd | kubectl delete --ignore-not-found=$(ignore-not-found) -f -
 
 .PHONY: deploy
 deploy: manifests kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
-	cd config/manager && $(KUSTOMIZE) edit set image controller=${CONTROLLER_IMG}
-	$(KUSTOMIZE) build config/default | $(KUBECTL) apply -f -
+	cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}
+	$(KUSTOMIZE) build config/default | kubectl apply -f -
 
 .PHONY: undeploy
-undeploy: kustomize ## Undeploy controller from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
-	$(KUSTOMIZE) build config/default | $(KUBECTL) delete --ignore-not-found=$(ignore-not-found) -f -
+undeploy: ## Undeploy controller from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
+	$(KUSTOMIZE) build config/default | kubectl delete --ignore-not-found=$(ignore-not-found) -f -
 
-##@ Dependencies
+##@ Build Dependencies
 
 ## Location to install dependencies to
 LOCALBIN ?= $(shell pwd)/bin
@@ -159,48 +134,132 @@ $(LOCALBIN):
 	mkdir -p $(LOCALBIN)
 
 ## Tool Binaries
-KUBECTL ?= kubectl
-KUSTOMIZE ?= $(LOCALBIN)/kustomize-$(KUSTOMIZE_VERSION)
-CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen-$(CONTROLLER_TOOLS_VERSION)
-ENVTEST ?= $(LOCALBIN)/setup-envtest-$(ENVTEST_VERSION)
-GOLANGCI_LINT = $(LOCALBIN)/golangci-lint-$(GOLANGCI_LINT_VERSION)
+KUSTOMIZE ?= $(LOCALBIN)/kustomize
+CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
+ENVTEST ?= $(LOCALBIN)/setup-envtest
 
 ## Tool Versions
-KUSTOMIZE_VERSION ?= v5.4.1
-CONTROLLER_TOOLS_VERSION ?= v0.17.1
-ENVTEST_VERSION ?= release-0.18
-GOLANGCI_LINT_VERSION ?= v2.1.6
+KUSTOMIZE_VERSION ?= v3.8.7
+CONTROLLER_TOOLS_VERSION ?= v0.13.0
 
+KUSTOMIZE_INSTALL_SCRIPT ?= "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
 .PHONY: kustomize
-kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
+kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary. If wrong version is installed, it will be removed before downloading.
 $(KUSTOMIZE): $(LOCALBIN)
-	$(call go-install-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v5,$(KUSTOMIZE_VERSION))
+	@if test -x $(LOCALBIN)/kustomize && ! $(LOCALBIN)/kustomize version | grep -q $(KUSTOMIZE_VERSION); then \
+		echo "$(LOCALBIN)/kustomize version is not expected $(KUSTOMIZE_VERSION). Removing it before installing."; \
+		rm -rf $(LOCALBIN)/kustomize; \
+	fi
+	test -s $(LOCALBIN)/kustomize || { curl -Ss $(KUSTOMIZE_INSTALL_SCRIPT) | bash -s -- $(subst v,,$(KUSTOMIZE_VERSION)) $(LOCALBIN); }
 
 .PHONY: controller-gen
-controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
+controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary. If wrong version is installed, it will be overwritten.
 $(CONTROLLER_GEN): $(LOCALBIN)
-	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))
+	test -s $(LOCALBIN)/controller-gen && $(LOCALBIN)/controller-gen --version | grep -q $(CONTROLLER_TOOLS_VERSION) || \
+	GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)
 
 .PHONY: envtest
-envtest: $(ENVTEST) ## Download setup-envtest locally if necessary.
+envtest: $(ENVTEST) ## Download envtest-setup locally if necessary.
 $(ENVTEST): $(LOCALBIN)
-	$(call go-install-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest,$(ENVTEST_VERSION))
+	test -s $(LOCALBIN)/setup-envtest || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
 
-.PHONY: golangci-lint
-golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
-$(GOLANGCI_LINT): $(LOCALBIN)
-	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,${GOLANGCI_LINT_VERSION})
+##@ RDM Migration Specific
 
-# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
-# $1 - target path with name of binary (ideally with version)
-# $2 - package url which can be installed
-# $3 - specific version of package
-define go-install-tool
-@[ -f $(1) ] || { \
-set -e; \
-package=$(2)@$(3) ;\
-echo "Downloading $${package}" ;\
-GOBIN=$(LOCALBIN) go install $${package} ;\
-mv "$$(echo "$(1)" | sed "s/-$(3)$$//")" $(1) ;\
-}
-endef
+.PHONY: generate-rdm
+generate-rdm: controller-gen ## Generate SharedRDM specific code and manifests.
+	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./api/v1alpha1/sharedrdm_types.go"
+	$(CONTROLLER_GEN) rbac:roleName=sharedrdm-manager-role crd webhook paths="./api/v1alpha1/sharedrdm_types.go" output:crd:artifacts:config=config/crd/bases output:rbac:artifacts:config=config/rbac
+
+.PHONY: test-rdm-integration
+test-rdm-integration: manifests generate fmt vet envtest ## Run RDM integration tests.
+	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./internal/controller/sharedrdm_controller_test.go ./pkg/utils/credutils_test.go -tags=integration -coverprofile cover-rdm-integration.out
+
+.PHONY: verify-rdm-crds
+verify-rdm-crds: manifests ## Verify SharedRDM CRDs are properly generated.
+	@echo "Verifying SharedRDM CRDs..."
+	@test -f config/crd/bases/vjailbreak.k8s.pf9.io_sharedrdms.yaml || (echo "SharedRDM CRD not found" && exit 1)
+	@echo "SharedRDM CRDs verified successfully"
+
+.PHONY: lint-rdm
+lint-rdm: ## Run linting specifically for RDM-related code.
+	golangci-lint run ./api/v1alpha1/sharedrdm_types.go ./internal/controller/sharedrdm_controller.go
+
+##@ Code Quality
+
+.PHONY: lint
+lint: ## Run golangci-lint on the codebase.
+	golangci-lint run
+
+.PHONY: security-scan
+security-scan: ## Run security scanning on the codebase.
+	gosec ./...
+
+.PHONY: dependency-check
+dependency-check: ## Check for known vulnerabilities in dependencies.
+	go list -json -deps ./... | nancy sleuth
+
+##@ Documentation
+
+.PHONY: docs-generate
+docs-generate: ## Generate API documentation.
+	go run hack/gen-docs.go
+
+.PHONY: docs-serve
+docs-serve: ## Serve documentation locally.
+	cd docs && hugo serve
+
+##@ Release
+
+.PHONY: release-build
+release-build: test lint security-scan ## Build release artifacts.
+	goreleaser build --snapshot --rm-dist
+
+.PHONY: release-snapshot
+release-snapshot: ## Create a snapshot release.
+	goreleaser release --snapshot --rm-dist
+
+##@ Cleanup
+
+.PHONY: clean
+clean: ## Clean build artifacts and temporary files.
+	rm -rf bin/
+	rm -rf dist/
+	rm -f cover*.out
+	docker system prune -f
+
+.PHONY: clean-crds
+clean-crds: ## Remove generated CRD files.
+	rm -f config/crd/bases/*.yaml
+
+##@ Development Helpers
+
+.PHONY: dev-setup
+dev-setup: ## Set up development environment.
+	@echo "Setting up development environment..."
+	go mod download
+	$(MAKE) controller-gen
+	$(MAKE) kustomize
+	$(MAKE) envtest
+	@echo "Development environment ready!"
+
+.PHONY: quick-test
+quick-test: fmt vet ## Run quick tests without full build.
+	go test -short ./...
+
+.PHONY: watch-test
+watch-test: ## Watch for changes and run tests automatically.
+	find . -name "*.go" | entr -c make quick-test
+
+##@ CI/CD
+
+.PHONY: ci-test
+ci-test: manifests generate fmt vet envtest lint security-scan ## Run all CI tests.
+	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./... -coverprofile cover.out -race -timeout 10m
+
+.PHONY: ci-build
+ci-build: ci-test ## Build for CI/CD pipeline.
+	$(MAKE) docker-build
+
+.PHONY: pre-commit
+pre-commit: fmt vet lint quick-test ## Run pre-commit checks.
+	@echo "Pre-commit checks passed!"
diff --git a/v2v-helper/Dockerfile b/v2v-helper/Dockerfile
--- a/v2v-helper/Dockerfile
+++ b/v2v-helper/Dockerfile
@@ -1,52 +1,181 @@
-# Stage 1: Build environment
-# Using Fedora 42 which includes Go 1.24 required by our go.mod
-FROM fedora:42 AS builder
-
-# Build arguments for multi-platform support and versioning
-ARG TARGETOS
-ARG TARGETARCH
-ARG RELEASE_VERSION
-ENV RELEASE_VERSION=$RELEASE_VERSION
+# Multi-stage build for optimized image size
+FROM ubuntu:22.04 as builder
 
 # Install build dependencies
-# - golang: Required for building the application (Go 1.24.1 from Fedora 42)
-# - libnbd-devel: Development files for NBD (Network Block Device) support
-RUN dnf install -y golang libnbd-devel
+RUN apt-get update && apt-get install -y \
+    wget \
+    curl \
+    ca-certificates \
+    && rm -rf /var/lib/apt/lists/*
 
-# Set up build workspace
-WORKDIR /workspace
+# Download and prepare any additional tools that need compilation
+# (This stage can be used for building custom tools if needed)
 
-# Copy pre-built binary from local build
-# Note: The binary is built by 'make -C v2v-helper build' before docker build
-# This is part of the VM migration toolchain for converting between different platforms
-COPY manager manager
+# Main runtime image
+FROM ubuntu:22.04
 
-# Stage 2: Runtime environment
-# Using same Fedora version for consistency and required runtime dependencies
-FROM fedora:42
+LABEL maintainer="vJailbreak Team <support@traycer.ai>"
+LABEL description="v2v-helper container with RDM migration support"
 
-# Add virtio-win repository for Windows drivers
-# Required for VM migration and conversion support
-# This provides Windows VirtIO drivers needed during VM conversion
-ADD https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo /etc/yum.repos.d/virtio-win.repo
-WORKDIR /tmp
-RUN curl -L -o virt-v2v-2.7.13-1.fc42.x86_64.rpm https://github.com/platform9/vjailbreak/raw/refs/heads/main/assets/rpms/virt-v2v-2.7.13-1.fc42.x86_64.rpm
+# Set environment variables
+ENV DEBIAN_FRONTEND=noninteractive
+ENV PATH="/usr/local/bin:$PATH"
 
-# Install runtime dependencies:
-# - nbdkit: Network Block Device toolkit for accessing disk images
-# - nbdkit-vddk-plugin: VMware VDDK plugin for accessing VMware disks
-# - libnbd: Network Block Device client library
-# - virt-v2v: Convert VMs between platforms (e.g., VMware to OpenStack)
-# - virtio-win: VirtIO drivers for Windows guests
-RUN dnf install -y \
-    nbdkit \
-    nbdkit-vddk-plugin \
-    libnbd \
-    virtio-win 
-    
-RUN dnf install -y /tmp/virt-v2v-2.7.13-1.fc42.x86_64.rpm && \
-    dnf clean all && \
-    rm -rf /var/cache/dnf
+# Install system packages and RDM migration tools
+RUN apt-get update && apt-get install -y \
+    # Basic system tools
+    bash \
+    coreutils \
+    util-linux \
+    procps \
+    # Device management and discovery tools
+    lsblk \
+    lsscsi \
+    sg3-utils \
+    udev \
+    kmod \
+    # Data copying and monitoring tools
+    pv \
+    rsync \
+    dd \
+    # Checksum and validation tools
+    coreutils \
+    # Network and storage tools
+    nbd-client \
+    open-iscsi \
+    multipath-tools \
+    # System monitoring and debugging
+    strace \
+    ltrace \
+    iostat \
+    iotop \
+    # JSON processing for API interactions
+    jq \
+    # Network tools
+    curl \
+    wget \
+    netcat-openbsd \
+    # Compression tools
+    gzip \
+    bzip2 \
+    xz-utils \
+    # File system tools
+    e2fsprogs \
+    xfsprogs \
+    dosfstools \
+    # Python for scripting
+    python3 \
+    python3-pip \
+    # SSL certificates
+    ca-certificates \
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get clean
 
-# Copy the binary from builder stage to the runtime environment
-COPY --from=builder /workspace/manager /home/fedora/manager
+# Install Python packages for OpenStack integration
+RUN pip3 install --no-cache-dir \
+    python-cinderclient \
+    python-novaclient \
+    python-keystoneclient \
+    requests \
+    pyyaml
+
+# Create necessary directories
+RUN mkdir -p /app \
+    /var/log/v2v-helper \
+    /tmp/rdm-migration \
+    /dev/mapper
+
+# Copy application binaries (these would be built in CI/CD)
+COPY --from=builder /usr/local/bin/* /usr/local/bin/ 2>/dev/null || true
+COPY v2v-helper /app/
+COPY scripts/ /app/scripts/
+
+# Set up device access permissions
+RUN groupadd -r storage && \
+    useradd -r -g storage -s /bin/bash v2v-helper && \
+    usermod -a -G disk,storage v2v-helper
+
+# Create wrapper script for device access
+RUN cat > /app/device-wrapper.sh << 'EOF'
+#!/bin/bash
+# Wrapper script to ensure proper device access for RDM operations
+
+# Scan for new devices
+echo "Scanning for storage devices..."
+/usr/bin/rescan-scsi-bus.sh -a 2>/dev/null || true
+udevadm settle
+
+# List available block devices for debugging
+echo "Available block devices:"
+lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,UUID
+
+# List SCSI devices
+echo "SCSI devices:"
+lsscsi -v 2>/dev/null || true
+
+# Execute the main application
+exec "$@"
+EOF
+
+RUN chmod +x /app/device-wrapper.sh
+
+# Create health check script
+RUN cat > /app/healthcheck.sh << 'EOF'
+#!/bin/bash
+# Health check for v2v-helper with RDM support
+
+# Check if main process is running
+if ! pgrep -f "v2v-helper" > /dev/null; then
+    echo "v2v-helper process not found"
+    exit 1
+fi
+
+# Check device access
+if ! ls /dev/sd* > /dev/null 2>&1 && ! ls /dev/nvme* > /dev/null 2>&1; then
+    echo "No block devices accessible"
+    exit 1
+fi
+
+# Check required tools
+for tool in lsblk lsscsi pv dd; do
+    if ! command -v "$tool" > /dev/null; then
+        echo "Required tool $tool not found"
+        exit 1
+    fi
+done
+
+echo "Health check passed"
+exit 0
+EOF
+
+RUN chmod +x /app/healthcheck.sh
+
+# Set working directory
+WORKDIR /app
+
+# Set proper ownership
+RUN chown -R v2v-helper:storage /app /var/log/v2v-helper /tmp/rdm-migration
+
+# Switch to non-root user for security
+USER v2v-helper
+
+# Expose any necessary ports (adjust as needed)
+EXPOSE 8080
+
+# Health check
+HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
+    CMD /app/healthcheck.sh
+
+# Set capabilities and security options in deployment manifests:
+# securityContext:
+#   capabilities:
+#     add:
+#       - SYS_ADMIN
+#       - SYS_RAWIO
+#       - MKNOD
+#   privileged: false
+#   allowPrivilegeEscalation: true
+
+# Default command
+ENTRYPOINT ["/app/device-wrapper.sh"]
+CMD ["/app/v2v-helper"]
